<template>
    <div>
        <b-jumbotron fluid header="Vote Online - Secured by Blockchain" lead="Welcome to transparency! Vote efficiently, effectively and securely.">
            <p>Please login by entering your details below. Your Voter ID is generated by the system and was securely sent to your registered phone number. The Member ID is the official number given to you by your institution. We will send you an OTP via SMS for verification. Everything is tracked by our blockchain technology!</p>
            <!-- <b-button block variant="primary" href="#" @click="modalShow = !modalShow">Login</b-button> -->
            <hr class="my-4">
            <b-row>
            <b-col sm="4">
              <b-form @submit="Login">
                  <b-input-group class="mb-2">
                      <b-col sm="4"><label for="email_id">Voter ID</label></b-col>
                      <b-col sm="8">
                        <b-form-input
                          v-model="voterID"
                        ></b-form-input>
                      </b-col>
                  </b-input-group>
                  <b-input-group class="mb-2">
                      <b-col sm="4"><label for="name_id">Member ID</label></b-col>
                      <b-col sm="8">
                        <b-form-input
                          v-model="memberID"
                        ></b-form-input>
                      </b-col>
                  </b-input-group>
                  <b-input-group class="mb-2" v-show="timeToEnterOtp">
                      <b-col sm="4"><label for="gender_id">OTP Code</label></b-col>
                      <b-col sm="8">
                        <b-form-input
                          v-model="otpCode"
                        ></b-form-input>
                      </b-col>
                  </b-input-group>
                  <b-button variant="primary" v-show="!timeToEnterOtp" @click="Login">Verify</b-button>
                  <b-button type="submit" variant="primary" v-show="timeToEnterOtp">Login</b-button>
                </b-form>
              </b-col>
              <img src="../../assets/ethereum.png" alt="" height="150em">
              <b-col sm="8">
              </b-col>
            </b-row>
            <hr class="my-4">
        </b-jumbotron>
        <div>

            <b-modal ref="login-modal"  v-model="modalShow">
               <b-input-group prepend="Voter ID: " class="mt-3">
                <b-form-input id="voter-id" v-model="voterID"></b-form-input>
              </b-input-group>
              <b-input-group prepend="Member ID: " class="mt-3">
                <b-form-input id="member-id" v-model="memberID"></b-form-input>
              </b-input-group>
              <b-input-group prepend="OTP Code: " v-show="timeToEnterOtp" class="mt-3">
                <b-form-input id="otp-code" v-model="otpCode"></b-form-input>
              </b-input-group>
              <button @click="Login">Login</button>
            </b-modal>
        </div>
    </div>
</template>

<script>
export default {
  data () {
    return {
      modalShow: false,
      timeToEnterOtp: false,
      memberID: '',
      voterID: '',
      otpCode: ''
    }
  },
  props: ['base_url'],
  methods: {
    async courier (url = '', data = {}, method = 'POST') {
      console.log('URL - ' + url + ' data ' + data)
      const response = await fetch(url, {
        method: method,
        mode: 'cors',
        cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
        credentials: 'same-origin', // include, *same-origin, omit
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'token 23c47112f527d06:fe249cb367f6a03'
          // 'Content-Type': 'application/x-www-form-urlencoded',
        },
        redirect: 'follow', // manual, *follow, error
        referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
        body: JSON.stringify(data)
      })
      const res = await response.json()
      console.log('RETURN: ' + JSON.stringify(res))
      return res
    },
    formatterUpperCase (value) {
      return value.toUpperCase()
    },
    Login: async function () {
      if (!this.timeToEnterOtp) {
        // post_memberID_and_voterID() and send OTP to user. Show OTP box
        // USE THE ENDPOINT: base_url + vote.utils.election_details.send_otp {‘voter_id’: ‘V000012’, 'member_id': ''}
        let args = {'voter_id': this.voterID, 'member_id': this.memberID}
        let url = `${this.base_url}/vote.utils.election_details.authenticate_voter`
        let method = 'POST'
        const loginrequest = await this.courier(url, args, method)
        console.log(JSON.stringify('LOGINREQ: ' + loginrequest))
        this.timeToEnterOtp = true
        return loginrequest
      } else {
        // VERYFY OTP.
        // use vote.utils.election_details.authenticate_voter {‘voter_id’: ‘V00012’,‘otp_code’: ‘47467chjue’} success - ‘message’:’OTP Code Valid’. Also default election

        this.$refs['login-modal'].hide()
        this.$emit('login-succeeded', this.memberID)
        return this.memberID
      }
    }
  }
}
</script>
